/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.unclediga.example.app;

import ru.unclediga.example.list.LinkedList;

import static ru.unclediga.example.utilities.StringUtils.join;
import static ru.unclediga.example.utilities.StringUtils.split;
import static ru.unclediga.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
